### ISSUE TITLE
Cannot build on plasma 5.27 beta

### ISSUE THREAD

**Issue by kde-yyds** [zzag/kwin-effects-cube#8]
```
user@user-vlrwx9 ~/src> git clone https://ghproxy.com/github.com/zzag/kwin-effects-cube
正克隆到 'kwin-effects-cube'...
remote: Enumerating objects: 385, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 385 (delta 14), reused 20 (delta 9), pack-reused 357
接收对象中: 100% (385/385), 1.06 MiB | 1011.00 KiB/s, 完成.
处理 delta 中: 100% (264/264), 完成.
user@user-vlrwx9 ~/src> cd kwin-effects-cube/
user@user-vlrwx9 ~/s/kwin-effects-cube (main)> mkdir build
user@user-vlrwx9 ~/s/kwin-effects-cube (main)> cd build/
user@user-vlrwx9 ~/s/k/build (main)> cmake .. -DCMAKE_INSTALL_PREFIX=/usr/
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Installing in the same prefix as Qt, adopting their path scheme.
-- Setting build type to 'Debug' as none was specified.
-- Looking for __GLIBC__
-- Looking for __GLIBC__ - found
-- Performing Test _OFFT_IS_64BIT
-- Performing Test _OFFT_IS_64BIT - Success
-- Performing Test HAVE_DATE_TIME
-- Performing Test HAVE_DATE_TIME - Success
CMake Warning (dev) at /usr/share/ECM/modules/ECMFindModuleHelpers.cmake:113 (message):
  Your project should require at least CMake 3.16.0 to use FindKF5.cmake
Call Stack (most recent call first):
  /usr/share/ECM/find-modules/FindKF5.cmake:30 (ecm_find_package_version_check)
  CMakeLists.txt:26 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found KF5Config: /usr/lib/x86_64-linux-gnu/cmake/KF5Config/KF5ConfigConfig.cmake (found version "5.102.0") 
-- Found KF5ConfigWidgets: /usr/lib/x86_64-linux-gnu/cmake/KF5ConfigWidgets/KF5ConfigWidgetsConfig.cmake (found version "5.102.0") 
-- Found KF5CoreAddons: /usr/lib/x86_64-linux-gnu/cmake/KF5CoreAddons/KF5CoreAddonsConfig.cmake (found version "5.102.0") 
-- Found KF5GlobalAccel: /usr/lib/x86_64-linux-gnu/cmake/KF5GlobalAccel/KF5GlobalAccelConfig.cmake (found version "5.102.0") 
-- Found Gettext: /usr/bin/msgmerge (found version "0.21") 
-- Found KF5I18n: /usr/lib/x86_64-linux-gnu/cmake/KF5I18n/KF5I18nConfig.cmake (found version "5.102.0") 
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Found KF5WindowSystem: /usr/lib/x86_64-linux-gnu/cmake/KF5WindowSystem/KF5WindowSystemConfig.cmake (found version "5.102.0") 
-- Found KF5XmlGui: /usr/lib/x86_64-linux-gnu/cmake/KF5XmlGui/KF5XmlGuiConfig.cmake (found version "5.102.0") 
-- Found KF5: success (found suitable version "5.102.0", minimum required is "5.94.0") found components: Config ConfigWidgets CoreAddons GlobalAccel I18n WindowSystem XmlGui 
-- Found epoxy: /usr/lib/x86_64-linux-gnu/libepoxy.so (found version "1.5.10") 
CMake Warning (dev) at /usr/share/ECM/modules/ECMFindModuleHelpers.cmake:113 (message):
  Your project should require at least CMake 3.16.0 to use FindXCB.cmake
Call Stack (most recent call first):
  /usr/share/ECM/find-modules/FindXCB.cmake:67 (ecm_find_package_version_check)
  CMakeLists.txt:37 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found XCB_XCB: /usr/lib/x86_64-linux-gnu/libxcb.so (found version "1.15") 
-- Found XCB: /usr/lib/x86_64-linux-gnu/libxcb.so (found version "1.15") found components: XCB 
-- The following OPTIONAL packages have been found:

 * KF5Auth (required version >= 5.102.0)
 * KF5Codecs (required version >= 5.102.0)

-- The following REQUIRED packages have been found:

 * ECM
 * Qt5Network (required version >= 5.15.8)
 * Qt5Qml (required version >= 5.15.8)
 * Qt5QmlModels (required version >= 5.15.8)
 * Qt5Quick
 * Qt5 (required version >= 5.15.0)
 * KF5GlobalAccel (required version >= 5.94.0)
 * Gettext
 * KF5I18n (required version >= 5.94.0)
 * KF5XmlGui (required version >= 5.94.0)
 * KF5 (required version >= 5.94.0)
 * epoxy
 * XCB, X protocol C-language Binding, <https://xcb.freedesktop.org/>
 * Qt5DBus (required version >= 5.15.2)
 * KF5Config (required version >= 5.98.0)
 * Qt5Core (required version >= 5.15.2)
 * KF5CoreAddons (required version >= 5.98.0)
 * Qt5Gui (required version >= 5.15.2)
 * KWinEffects (required version >= 5.25.0)
 * KWinDBusInterface

-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/src/kwin-effects-cube/build
user@user-vlrwx9 ~/s/k/build (main)> make -j16
[ 11%] Automatic MOC for target kwin4_effect_cube
[ 11%] Automatic MOC for target kwin_cube_config
[ 11%] Built target kwin4_effect_cube_autogen
[ 17%] Generating cubeconfig.h, cubeconfig.cpp
[ 17%] Built target kwin_cube_config_autogen
[ 29%] Generating ui_cubeeffectkcm.h
[ 29%] Generating cubeconfig.h, cubeconfig.cpp
[ 35%] Generating kwineffects_interface.cpp, kwineffects_interface.h
[ 41%] Building CXX object src/CMakeFiles/kwin4_effect_cube.dir/kwin4_effect_cube_autogen/mocs_compilation.cpp.o
[ 47%] Building CXX object src/CMakeFiles/kwin4_effect_cube.dir/cubeconfig.cpp.o
[ 52%] Building CXX object src/CMakeFiles/kwin4_effect_cube.dir/cubeeffect.cpp.o
[ 58%] Building CXX object src/CMakeFiles/kwin4_effect_cube.dir/main.cpp.o
[ 64%] Generating kwineffects_interface.moc
[ 70%] Building CXX object src/kcm/CMakeFiles/kwin_cube_config.dir/cubeeffectkcm.cpp.o
[ 76%] Building CXX object src/kcm/CMakeFiles/kwin_cube_config.dir/cubeconfig.cpp.o
[ 82%] Building CXX object src/kcm/CMakeFiles/kwin_cube_config.dir/kwin_cube_config_autogen/mocs_compilation.cpp.o
[ 88%] Building CXX object src/kcm/CMakeFiles/kwin_cube_config.dir/kwineffects_interface.cpp.o
In file included from /usr/include/kwinquickeffect.h:9,
                 from /home/user/src/kwin-effects-cube/src/cubeeffect.h:9,
                 from /home/user/src/kwin-effects-cube/src/main.cpp:7:
/usr/include/kwineffects.h:3010:15: error: ‘std::span’ has not been declared
 3010 |     void copy(std::span<GLVertex2D> destination);
      |               ^~~
/usr/include/kwineffects.h:3010:24: error: expected ‘,’ or ‘...’ before ‘<’ token
 3010 |     void copy(std::span<GLVertex2D> destination);
      |                        ^
In file included from /usr/include/kwinquickeffect.h:9,
                 from /home/user/src/kwin-effects-cube/build/src/kwin4_effect_cube_autogen/EWIEGA46WW/../../../../src/cubeeffect.h:9,
                 from /home/user/src/kwin-effects-cube/build/src/kwin4_effect_cube_autogen/EWIEGA46WW/moc_cubeeffect.cpp:10,
                 from /home/user/src/kwin-effects-cube/build/src/kwin4_effect_cube_autogen/mocs_compilation.cpp:2:
/usr/include/kwineffects.h:3010:15: error: ‘std::span’ has not been declared
 3010 |     void copy(std::span<GLVertex2D> destination);
      |               ^~~
/usr/include/kwineffects.h:3010:24: error: expected ‘,’ or ‘...’ before ‘<’ token
 3010 |     void copy(std::span<GLVertex2D> destination);
      |                        ^
In file included from /usr/include/kwinquickeffect.h:9,
                 from /home/user/src/kwin-effects-cube/src/cubeeffect.h:9,
                 from /home/user/src/kwin-effects-cube/src/cubeeffect.cpp:7:
/usr/include/kwineffects.h:3010:15: error: ‘std::span’ has not been declared
 3010 |     void copy(std::span<GLVertex2D> destination);
      |               ^~~
/usr/include/kwineffects.h:3010:24: error: expected ‘,’ or ‘...’ before ‘<’ token
 3010 |     void copy(std::span<GLVertex2D> destination);
      |                        ^
make[2]: *** [src/CMakeFiles/kwin4_effect_cube.dir/build.make:113：src/CMakeFiles/kwin4_effect_cube.dir/main.cpp.o] 错误 1
make[2]: *** 正在等待未完成的任务....
make[2]: *** [src/CMakeFiles/kwin4_effect_cube.dir/build.make:85：src/CMakeFiles/kwin4_effect_cube.dir/kwin4_effect_cube_autogen/mocs_compilation.cpp.o] 错误 1
/home/user/src/kwin-effects-cube/src/cubeeffect.cpp: In constructor ‘KWin::CubeEffect::CubeEffect()’:
/home/user/src/kwin-effects-cube/src/cubeeffect.cpp:36:14: error: ‘class KWin::EffectsHandler’ has no member named ‘registerGlobalShortcut’; did you mean ‘registerAxisShortcut’?
   36 |     effects->registerGlobalShortcut({defaultToggleShortcut}, m_toggleAction);
      |              ^~~~~~~~~~~~~~~~~~~~~~
      |              registerAxisShortcut
/home/user/src/kwin-effects-cube/src/cubeeffect.cpp: In member function ‘void KWin::CubeEffect::deactivate()’:
/home/user/src/kwin-effects-cube/src/cubeeffect.cpp:156:30: error: ‘views’ was not declared in this scope; did you mean ‘viewAt’?
  156 |     const auto screenViews = views();
      |                              ^~~~~
      |                              viewAt
make[2]: *** [src/CMakeFiles/kwin4_effect_cube.dir/build.make:99：src/CMakeFiles/kwin4_effect_cube.dir/cubeeffect.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:441：src/CMakeFiles/kwin4_effect_cube.dir/all] 错误 2
make[1]: *** 正在等待未完成的任务....
[ 94%] Linking CXX shared module kwin_cube_config.so
[ 94%] Built target kwin_cube_config
make: *** [Makefile:146：all] 错误 2
user@user-vlrwx9 ~/s/k/build (main) [2]> 

```

**Comment by zzag** [comment]
Should be fixed

**Comment by jjgalvez** [comment]
Trying to build this morning, and just to be clear with this commit the package won't build without kwin 5.27.  No action requested just validating

**Comment by zzag** [comment]
Yes, you need 5.27

**Comment by jjgalvez** [comment]
> Yes, you need 5.27

thanks I'll wait for 5.27 before I try to update

**Comment by zzag** [comment]
> > Yes, you need 5.27
> 
> thanks I'll wait for 5.27 before I try to update

You can checkout older version, which builds with 5.26, too

```
git checkout 1.0.0
```

**Comment by zzag** [comment]
or download the corresponding source tarball from the release page
